# Generated by Django 3.1.7 on 2021-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='Rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
