# Generated by Django 3.1.7 on 2021-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeroApp', '0003_auto_20210311_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='Rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
